
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqugykrnwgoeepygjwsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxdWd5a3Jud2dvZWVweWdqd3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDYxMzUsImV4cCI6MjA2MTU4MjEzNX0.rwoYY7N8VIBCJdHgtf_oXnSCY0YcAq8E5pJm_lyIe1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Currency conversion (USD to INR)
export const USD_TO_INR_RATE = 83;

// Helper function to format price in rupees
export const formatRupees = (amount: number) => {
  return `₹${(amount).toLocaleString('en-IN')}`;
};
